server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    properties:
      spring.json.trusted.packages: ${TRUSTED_PACKAGES}
    producer:
      key-serializer: "org.apache.kafka.common.serialization.UUIDSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      acks: all
      retries: 10
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.UUIDDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
