server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_URL}/realms/${REALM}
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: accounting-service
          uri: lb://ACCOUNTING-SERVICE
          predicates:
            - Path=/accounting/**

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/**

        - id: profiler-service
          uri: lb://PROFILER-SERVICE
          predicates:
            - Path=/profiler/**

        - id: promotion-service
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/api/v1/promotion/**  
