spring:
  application:
    name: NOTIFICATION-SERVICE
  kafka:
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest  

app:
  kafka:
    topics:
      notification: ${NOTIFICATION_TOPIC}
    topic-properties:
      name: ${NOTIFICATION_TOPIC}
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
    retry:
      interval: 1000
      max-attempts: 2
