server:
  port: ${SERVER_PORT}

app:
  accounting:
    url: ${ACCOUNTING_URL}
  security:
    url: ${SECURITY_URL}
  profile:
    url: ${PROFILE_URL}
  kafka:
    topics:
      promotion: ${PROMOTION_TOPIC}
      accounting: ${ACCOUNTING_TOPIC}
      security: ${SECURITY_TOPIC}
      profiler: ${PROFILER_TOPIC}
      notification: ${NOTIFICATION_TOPIC}
    topic-properties:
      name: ${PROMOTION_TOPIC}
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
    retry:
      interval: 1000
      max-attempts: 2  

spring:
  application:
    name: promotion-service
  kafka:
    consumer:
      group-id: accounting-service-group
      auto-offset-reset: latest  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_URL}/realms/${REALM}
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
