server:
  port: ${SERVER_PORT}

app:
  accounting:
    url: ${ACCOUNTING_URL}
  security:
    url: ${SECURITY_URL}
  profile:
    url: ${PROFILE_URL}

spring:
  application:
    name: promotion-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8079/realms/m.tyumentsev/protocol/openid-connect/certs
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
