spring:
  application:
    name: SECURITY-SERVICE
  kafka:
    consumer:
      group-id: security-service-group
      auto-offset-reset: earliest  

app:
  kafka:
    topics:
      security: ${SECURITY_TOPIC}
      promotion: ${PROMOTION_TOPIC}
    topic-properties:
      name: ${SECURITY_TOPIC}
      partitions: 3
      replicas: 3
      min-in-sync-replicas: 2
    retry:
      interval: 1000
      max-attempts: 2
